@extends('layouts.app')
@section('title', 'Health Profile')

@section('content')

{{-- Header --}}
<div class="px-8 py-6 bg-white border-b border-gray-200 flex-shrink-0 flex items-center justify-between">
    <div>
        <h1 class="text-xl font-bold text-gray-900">Health Profile</h1>
        <p class="text-gray-500 text-sm mt-0.5">Your AI-analysed medical insights</p>
    </div>
    <div class="flex gap-3">
        <button onclick="getRecommendations()"
                class="px-4 py-2 text-sm font-medium text-emerald-700 bg-emerald-50 hover:bg-emerald-100 rounded-lg transition-colors border border-emerald-200">
            ✦ Get Recommendations
        </button>
        <button onclick="shareProfile()"
                class="px-4 py-2 text-white text-sm font-medium rounded-lg transition-colors"
                style="background: linear-gradient(135deg, #10b981, #2563eb);">
            Share Profile
        </button>
    </div>
</div>

<div class="flex-1 px-8 py-6 space-y-6">

    {{-- Disclaimer --}}
    <div class="flex items-start gap-3 px-4 py-3 bg-blue-50 border border-blue-200 rounded-xl text-blue-700 text-xs">
        <svg class="w-4 h-4 flex-shrink-0 mt-0.5" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"/>
        </svg>
        <span>These are <strong>informational insights only</strong>, generated by AI from your uploaded documents. They are not medical advice. Always consult a qualified healthcare provider.</span>
    </div>

    {{-- Share result --}}
    <div id="shareResult" class="hidden px-4 py-3 bg-emerald-50 border border-emerald-200 rounded-xl text-sm text-emerald-700">
        <p class="font-medium mb-1">Shareable link created (valid 30 days):</p>
        <div class="flex items-center gap-2">
            <code id="shareUrl" class="flex-1 bg-white border border-emerald-200 rounded px-2 py-1 text-xs text-emerald-900 break-all"></code>
            <button onclick="copyShareUrl()" class="px-3 py-1 bg-emerald-100 hover:bg-emerald-200 rounded text-xs font-medium transition-colors">Copy</button>
        </div>
    </div>

    {{-- Recommendations panel --}}
    <div id="recommendationsPanel" class="hidden bg-white rounded-xl border border-gray-200 p-6">
        <div class="flex items-center justify-between mb-4">
            <h2 class="font-semibold text-gray-900">Health Recommendations</h2>
            <button onclick="document.getElementById('recommendationsPanel').classList.add('hidden')"
                    class="text-gray-400 hover:text-gray-600 transition-colors">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
            </button>
        </div>
        <div id="recommendationsBody" class="grid grid-cols-1 lg:grid-cols-2 gap-4 text-sm"></div>
    </div>

    {{-- Medical Reports --}}
    <div>
        <div class="flex items-center gap-2 mb-3">
            <div class="w-6 h-6 rounded-lg bg-emerald-100 flex items-center justify-center">
                <svg class="w-3.5 h-3.5 text-emerald-700" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/>
                </svg>
            </div>
            <h2 class="font-semibold text-gray-900">Medical Reports</h2>
            <span class="text-xs text-gray-400">({{ $medicalReports->count() }})</span>
        </div>

        @if($medicalReports->isEmpty())
            <div class="bg-white rounded-xl border border-gray-200 p-8 text-center">
                <p class="text-gray-400 text-sm">No medical reports uploaded yet.</p>
                <a href="{{ route('dashboard') }}" class="text-emerald-600 text-sm hover:underline mt-1 inline-block">Upload a report →</a>
            </div>
        @else
            <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
                @foreach($medicalReports as $doc)
                <div class="bg-white rounded-xl border border-gray-200 p-5 hover:border-emerald-200 transition-colors">
                    <div class="flex items-start justify-between mb-3">
                        <div class="flex-1 min-w-0">
                            <p class="font-medium text-gray-900 truncate">{{ $doc->title }}</p>
                            <p class="text-xs text-gray-400 mt-0.5">{{ $doc->created_at->format('M j, Y') }}</p>
                        </div>
                        @if($doc->analysis_result)
                            @php $risk = $doc->analysis_result['risk_level'] ?? 'unknown'; @endphp
                            <span class="ml-3 flex-shrink-0 px-2.5 py-1 rounded-full text-xs font-semibold
                                {{ $risk === 'low' ? 'bg-green-100 text-green-700' : ($risk === 'medium' ? 'bg-amber-100 text-amber-700' : ($risk === 'high' ? 'bg-red-100 text-red-700' : 'bg-gray-100 text-gray-500')) }}">
                                {{ strtoupper($risk) }} RISK
                            </span>
                        @elseif($doc->status !== 'ready')
                            <span class="ml-3 flex-shrink-0 px-2.5 py-1 rounded-full text-xs font-medium bg-yellow-100 text-yellow-700">{{ $doc->status }}</span>
                        @endif
                    </div>

                    @if($doc->analysis_result)
                        @if(!empty($doc->analysis_result['summary']))
                            <p class="text-xs text-gray-600 mb-3 line-clamp-2">{{ $doc->analysis_result['summary'] }}</p>
                        @endif

                        @if(!empty($doc->analysis_result['key_findings']))
                            <div class="mb-3">
                                <p class="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">Key Findings</p>
                                <ul class="space-y-1">
                                    @foreach(array_slice($doc->analysis_result['key_findings'], 0, 3) as $finding)
                                        <li class="text-xs text-gray-600 flex items-start gap-1.5">
                                            <span class="text-emerald-500 mt-0.5">•</span>{{ $finding }}
                                        </li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                    @else
                        <div class="flex items-center gap-2 text-xs text-gray-400 py-2">
                            <span class="w-2 h-2 bg-amber-400 rounded-full animate-pulse"></span>
                            Analysis in progress…
                        </div>
                    @endif
                </div>
                @endforeach
            </div>
        @endif
    </div>

    {{-- Prescriptions --}}
    <div>
        <div class="flex items-center gap-2 mb-3">
            <div class="w-6 h-6 rounded-lg bg-blue-100 flex items-center justify-center">
                <svg class="w-3.5 h-3.5 text-blue-700" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z"/>
                </svg>
            </div>
            <h2 class="font-semibold text-gray-900">Prescriptions</h2>
            <span class="text-xs text-gray-400">({{ $prescriptions->count() }})</span>
        </div>

        @if($prescriptions->isEmpty())
            <div class="bg-white rounded-xl border border-gray-200 p-8 text-center">
                <p class="text-gray-400 text-sm">No prescriptions uploaded yet.</p>
                <a href="{{ route('dashboard') }}" class="text-blue-600 text-sm hover:underline mt-1 inline-block">Upload a prescription →</a>
            </div>
        @else
            <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
                @foreach($prescriptions as $doc)
                <div class="bg-white rounded-xl border border-gray-200 p-5 hover:border-blue-200 transition-colors">
                    <div class="flex items-start justify-between mb-3">
                        <div>
                            <p class="font-medium text-gray-900">{{ $doc->title }}</p>
                            <p class="text-xs text-gray-400 mt-0.5">{{ $doc->created_at->format('M j, Y') }}</p>
                        </div>
                        @if(!$doc->analysis_result && $doc->status !== 'ready')
                            <span class="px-2.5 py-1 rounded-full text-xs font-medium bg-yellow-100 text-yellow-700">{{ $doc->status }}</span>
                        @endif
                    </div>

                    @if($doc->analysis_result && !empty($doc->analysis_result['medicines']))
                        <div>
                            <p class="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Medicines</p>
                            <div class="space-y-2">
                                @foreach($doc->analysis_result['medicines'] as $med)
                                <div class="px-3 py-2 bg-blue-50 rounded-lg">
                                    <p class="text-xs font-semibold text-blue-900">{{ $med['name'] ?? 'Unknown' }}</p>
                                    <p class="text-xs text-blue-700 mt-0.5">{{ $med['dosage'] ?? '' }} · {{ $med['frequency'] ?? '' }}</p>
                                    @if(!empty($med['purpose']))
                                        <p class="text-xs text-gray-500 mt-0.5">{{ $med['purpose'] }}</p>
                                    @endif
                                </div>
                                @endforeach
                            </div>
                        </div>
                    @elseif($doc->analysis_result)
                        <p class="text-xs text-gray-400">Analysis complete — no medicines extracted.</p>
                    @else
                        <div class="flex items-center gap-2 text-xs text-gray-400 py-2">
                            <span class="w-2 h-2 bg-amber-400 rounded-full animate-pulse"></span>
                            Analysis in progress…
                        </div>
                    @endif
                </div>
                @endforeach
            </div>
        @endif
    </div>

</div>

@endsection

@push('scripts')
<script>
const TOKEN = '{{ session("api_token", "") }}';

async function getRecommendations() {
    const btn = event.target;
    btn.disabled = true;
    btn.textContent = 'Loading…';

    try {
        const res  = await fetch('/api/v1/health-profile/recommendations', {
            headers: { 'Authorization': 'Bearer ' + TOKEN, 'Accept': 'application/json' },
        });
        const data = await res.json();

        if (!res.ok) { alert(data.message || 'Failed to get recommendations.'); btn.disabled = false; btn.textContent = '✦ Get Recommendations'; return; }

        const panel = document.getElementById('recommendationsPanel');
        const body  = document.getElementById('recommendationsBody');
        body.innerHTML = '';

        const sections = [
            { key: 'diet_plan',         label: 'Diet Plan',          color: 'emerald' },
            { key: 'lifestyle_changes',  label: 'Lifestyle Changes',  color: 'blue' },
            { key: 'exercise_plan',      label: 'Exercise Plan',      color: 'purple' },
            { key: 'daily_routine',      label: 'Daily Routine',      color: 'amber' },
        ];

        sections.forEach(({ key, label, color }) => {
            if (data[key]?.length) {
                body.innerHTML += `
                    <div class="p-4 bg-${color}-50 rounded-xl border border-${color}-100">
                        <p class="text-xs font-semibold text-${color}-700 uppercase tracking-wide mb-2">${label}</p>
                        <ul class="space-y-1">${data[key].map(i => `<li class="text-xs text-gray-700 flex items-start gap-1.5"><span class="text-${color}-500 mt-0.5 flex-shrink-0">•</span>${i}</li>`).join('')}</ul>
                    </div>`;
            }
        });

        if (data.disclaimer) {
            body.innerHTML += `<div class="lg:col-span-2 p-3 bg-blue-50 rounded-lg text-xs text-blue-700 border border-blue-100">${data.disclaimer}</div>`;
        }

        panel.classList.remove('hidden');
        panel.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    } catch (e) {
        alert(e.message);
    }

    btn.disabled = false;
    btn.textContent = '✦ Get Recommendations';
}

async function shareProfile() {
    const btn = event.target;
    btn.disabled = true;
    btn.textContent = 'Generating…';

    try {
        const res  = await fetch('/api/v1/health-profile/share', {
            method: 'POST',
            headers: { 'Authorization': 'Bearer ' + TOKEN, 'Accept': 'application/json', 'Content-Type': 'application/json' },
        });
        const data = await res.json();

        if (!res.ok) { alert(data.message || 'Failed to create share link.'); btn.disabled = false; btn.textContent = 'Share Profile'; return; }

        document.getElementById('shareUrl').textContent = data.share_url;
        document.getElementById('shareResult').classList.remove('hidden');
        document.getElementById('shareResult').scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    } catch (e) {
        alert(e.message);
    }

    btn.disabled = false;
    btn.textContent = 'Share Profile';
}

function copyShareUrl() {
    const url = document.getElementById('shareUrl').textContent;
    navigator.clipboard.writeText(url).then(() => {
        const btn = event.target;
        btn.textContent = 'Copied!';
        setTimeout(() => btn.textContent = 'Copy', 2000);
    });
}
</script>
@endpush
